### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by nilsmoody** [r57zone/Harry-Potter-and-the-Chamber-of-Secrets-Xbox-gamepad#1]
I've replaced the INI-File but it doesn't work with my Xbox Series Xinput Controller. I've tested if the game was loading from the right file by deleting the jump command from right mouse and it is indeed loading the correct file. Is there anything I can do? It's about Harry Potter 2 btw,

**Comment by r57zone** [comment]
Hi, do you play wirelessly? try connecting wires

**Comment by nilsmoody** [comment]
Hi r57zone! Thank you for the response. :) Yeah, I do play wirelessly and unfortunately, my current setup does not allow for a wired controller. Is there no way to do this wirelessly?

**Comment by r57zone** [comment]
Probably in wireless mode, these configurations will not work. You need Antimicro https://github.com/AntiMicro/antimicro or JoyShockMapper.

**Comment by nilsmoody** [comment]
That's sad to hear. I'm already using JoyXoff which I found out to be the better of programs like that. Maybe I will create a profile for the game. Thanks for the support.

A greeting from Europe. It's great how such old games can connect people together.

**Comment by r57zone** [comment]
Yes, it's a great game and people are still playing it, it's great. I love the first 2 games.
