### ISSUE TITLE
Lack of broomstick acceleration/deceleration controls

### ISSUE THREAD

**Issue by Scvairy** [r57zone/Harry-Potter-and-the-Chamber-of-Secrets-Xbox-gamepad#2]
Is there a way to use a and z from the keyboard on the controller?

**Comment by r57zone** [comment]
LB & RB don't work for this?

**Comment by Scvairy** [comment]
I tried, but it seems not to work

**Comment by r57zone** [comment]
Looks like I fixed it. Try the new version of `User.ini`.

**Comment by Scvairy** [comment]
I tried to fix it the same way, and my game stopped working (maybe because of something else) and I deleted it, because I already completed the story yesterday😅
Thanks for the effort, I think I'll try `User.ini` in HP2 in the near future, and then come back with a feedback

**Comment by Scvairy** [comment]
I reinstalled the HP1 and tried, and now it is waaay better. Before I needed to use left stick to move, and the movement was confusing. Now I should use right stick (or mouse) - and it use shoulders to accelerate/decelerate, and I got perfect score on broomstick practice. Thank you!

upd. I used mods: HP1_Movement_and_Camera_Improvement and DirectX 9.
Without HP1_Movement_and_Camera_Improvement it can't move at all on broomstick, and in normal mode (without broomstick) it can't move sideways with left stick.

Also, when drawing a spell, left stick moves cursor only up and down, and right stick moves it in all directions. But you need to use right hand to hold square button...
